services:
  - type: web
    name: psyche-ai
    runtime: python
    rootDir: make-psychologist
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: ELEVENLABS_VOICE_ID
        value: EXAVITQu4vr4xnSDxMaL
